improve derivation of `BFieldCodec` for structs with only fixed-length fields
Neptune-Crypto/twenty-first pull request #125
Opened 2023-06-22 07:41 UTC by jan-ferdinand

Fix #124

2023-06-22 07:58 UTC, jan-ferdinand commented on twenty-first/src/shared_math/bfield_codec.rs
> +            }
I'm not super happy about this. The underlying requirement comes from initiating the result vector as `Vec::with_capacity(num_elements)` in `impl<T> BFieldCodec for Vec<T>::decode()`, which is nice to have but apparently introduces a DOS vector. The alternative is to use `vec![]` and bite the cost of internal re-allocations.

Thought, @Sword-Smith?

2023-06-22 08:07 UTC, jan-ferdinand commented on twenty-first/src/shared_math/bfield_codec.rs
> +            }
After writing above comment, I feel much more strongly inclined to use `vec![]` instead of `Vec::with_capacity(random_persons_claim)`.

2023-06-22 12:10 UTC, Sword-Smith requested changes
This certainly works in isolation, and it might be an improvement.

A significant change, though, is that the encoding of a `struct` no longer prepends the length of each field. This will break things downstream, especially things in https://github.com/TritonVM/tasm-lib/tree/asz/removal-record-integrity/src/structure.

It might be advantageous to always prepend the field length when encoding a struct, even if it is known at compile-time as that makes any TASM program that deals with these encodings simpler.

I think @aszepieniec should weigh in on this.

This new rule that @jan-ferdinand has programmed would mean that the field size is *not* prepended if it is known statically, otherwise the field size *is* prepended. It makes for shorter encodings, but also for potentially more complicated TASM programs to get a specific field from a struct.

2023-06-22 12:24 UTC, jan-ferdinand commented
Good point. I wasn't aware of such dependencies downstream. In isolation, it seems to me that my suggested solution is a rather clean approach. My hope is that the approach can be transferred to the TASM context as well.

2023-06-22 19:09 UTC, aszepieniec commented
If every field is length-prepended, then the procedure for "get field x" can be struct-agnostic simply by indexing and hopping over fields until a decrementing counter reaches zero. But if some fields are not length-prepended, then the "get field x" method has to be a custom method for every struct, for every field.

I started implementing a collection of "get field x" methods for `TransactionKernel` assuming (wrongly) that statically-sized fields are not length-prepended. The result was a monster. I'm very happy to use the generic "get nth field" method that works for any struct under the length-prepended encoding and I would strongly suggest we not change this property.

2023-06-26 10:38 UTC, Sword-Smith commented
After talking to @aszepieniec we have agreed that this proposal from @jan-ferdinand is the way we want to go. But please don't merge before conferring with @aszepieniec or me, as there will be downstream complications.

2023-06-29 09:26 UTC, Sword-Smith commented
@aszepieniec and myself should go over this new `BFieldCodec` derivation before merging, since we have the most experience working with these encodings in TASM.

- [ ] Approvable by @aszepieniec 
- [ ] Approvable by @Sword-Smith 
- [ ] Approvable by @jan-ferdinand (optional)

2023-06-29 09:27 UTC, Sword-Smith requested changes
No merge before approved by requested reviewers

2023-07-25 14:55 UTC, aszepieniec commented
Approved via #136

2023-07-25 14:55 UTC, closed without merging