refactor: Mmr tests no longer depend on storage layer
Neptune-Crypto/twenty-first pull request #189
Opened 2024-03-13 06:20 UTC by dan-da

Breaking Change

* adds src/mock that is built if `mock` feature-flag enabled
* removes `ArchivalMmr` and replaces with `MockMmr`, in memory
* removes `RustyLevelDbVec`, `DatabaseArray`, `DatabaseVec`
* use MockMmr instead of ArchivalMmr in Mmr tests

2024-03-13 07:56 UTC, aszepieniec approved these changes

2024-03-13 08:31 UTC, Sword-Smith requested changes
Looks good. I only request a few updates to documentation.

2024-03-13 08:31 UTC, Sword-Smith commented on twenty-first/src/mock/mmr/mock_mmr.rs
> +/// It implements an in-memory Mmr using a Vec<Digest> as the data store.
You should clarify that this is an archival-MMR, not an MMR accumulator. An archival MMR stores *all* nodes in multiple trees whereas an MMR accumulator only stores the roots of the binary trees.

This clarification could take place either in the documentation, or through the name of the mock struct. Up to you.

2024-03-13 08:31 UTC, Sword-Smith commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +            // 1. Build an MockMmr with a variable amount of leaves
'a' :)

2024-03-13 08:31 UTC, Sword-Smith commented on twenty-first/src/mock/mmr/mock_mmr.rs
> +                // Verify that membership proofs are the same as generating them from an MockMmr
'a' :)

2024-03-14 01:56 UTC, dan-da commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +            // 1. Build an MockMmr with a variable amount of leaves
done.

2024-03-14 01:56 UTC, dan-da commented on twenty-first/src/mock/mmr/mock_mmr.rs
> +                // Verify that membership proofs are the same as generating them from an MockMmr
done.

2024-03-14 02:06 UTC, merged