Einar/pr/misc
Neptune-Crypto/twenty-first pull request #29
Opened 2022-09-13 14:26 UTC by einar-triton

This PR fixes and adds miscellaneous things - some of them needed by the work on `neptune-core`.

* Fixes ` cargo build --all-targets`
* Implements `Display` instance for `U32s<N>`
* Implements `From<u64>` for `U32s<N>` 
* Implements `Deref` instance for our `Blake3Wrapper` as suggested by [_The Book_, ch. 15.2][The Book].
* Introduces `.mailmap` file for nicer git logs.  This is a copy from `neptune-core`.
* ` cargo build --all-targets  && cargo test --all && cargo clippy --all` succeeds except for a few slow tests.

[The Book]: https://doc.rust-lang.org/book/ch15-02-deref.html#treating-smart-pointers-like-regular-references-with-the-deref-trait

2022-09-13 17:30 UTC, sshine requested changes
- `impl<const N: usize> From<u64> for U32s<N>` is not well-defined.
- `impl Deref for Blake3Hash` does not seem useful. Use it or lose it.

2022-09-13 17:30 UTC, sshine commented on twenty-first/src/util_types/blake3_wrapper.rs
> +
> *... everywhere we need a `&blake3::Hash`.*

What places are those?

I believe the main purpose of blake3 at this point is for tests that use a lot of hashing to go faster.

2022-09-14 13:12 UTC, einar-triton commented on twenty-first/src/amount/u32s.rs
> +}
Good catch.  `N = 0` is already a problem in the existing [`From<u32>`](https://github.com/Neptune-Crypto/twenty-first/blob/0fdd70f497996efe8b62936bc425b9e2c33e73c4/twenty-first/src/amount/u32s.rs#L294-L300).  Maybe they should both be `TryFrom`?

2022-09-15 13:06 UTC, sshine commented on twenty-first/src/amount/u32s.rs
> +}
They probably should, yes! That'd be a breaking change, though.

2022-09-15 15:20 UTC, einar-triton commented on twenty-first/src/amount/u32s.rs
> +}
I am not ready to fix this right now, so I put a deactivated test, so we don't forget it.

2022-09-19 14:14 UTC, sshine approved these changes

2022-09-19 14:16 UTC, merged