Replace simple_hasher::Hasher with AlgebraicHasher
Neptune-Crypto/twenty-first pull request #44
Opened 2022-10-17 08:51 UTC by sshine

The AlgebraicHasher trait outputs a `Digest`, consisting of `DIGEST_LEN` `BFieldElement`s, no matter if `blake3::Hasher` or `RescuePrimeRegular` is used. This means that `blake3::Hasher` can be used throughout the pipeline, including in Triton VM where digests have an expected format and size.

In `simple_hasher`:
- Remove `Hasher`
- Remove `SamplableFrom` in favor of `XFieldElement::sample()`
- Move `Hashable` to `AlgebraicHasher`

Associated types and type parameters are hardcoded in `AlgebraicHasher`
- `Hashable`'s parameter is always `BFieldElement`
- `Hasher`'s `T` is always `BFieldElement`
- `Hasher`'s `Digest` (the associated type) is always `Digest` (the struct)

Refactor `.emojihash()`:
- Drop `.emojihash_raw()`
- Use `u64::to_be_bytes()` instead of Hasher's `.to_sequence()`

`impl Distribution<Digest> for Standard`:
- Makes `random_values()` capable of generating random digests.

Add `PhantomData<H>` back to:
- `MerkleTree`
- `MmrAccumulator`

...since they do not pass their 'H' onto their fields' types.

2022-10-17 08:51 UTC, sshine commented
**Note:** The last commit awaits one minor fix before it is reworded.

2022-10-17 10:48 UTC, Ulrik-dk requested changes
Most of my comments are on seemingly magical numbers, which are used in old tests, instead of the new random element function. In other places, genuinely magical numbers that are needed multiple places can be factored out, and referenced in these places.

This issue is many places in the code, and you're not responsible for that. Maybe it should be an issue on its own, to factor out magical numbers. Or to just be more conscious of it.

2022-10-17 10:48 UTC, Ulrik-dk commented on stark-brainfuck/src/stark.rs
>          timer.elapsed("combination_codeword");
This timer mark is now superfluous.

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/shared_math/fri.rs
> +            roots.push(proof_stream.dequeue(Digest::BYTES)?);
Thanks for getting rid of some of these magical constants.

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +            let new_leaf = H::hash(&BFieldElement::new(13333337));
Is this a magic number or a random Digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let new_leaf: Digest = H::hash(&133333333333333333333337u128);
PLACEHOLDER TEXT.

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let new_leaf: Digest = H::hash(&133333333333333333333337u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let new_leaf3: Digest = H::hash(&12345678u128);
`new_leaf2` and `new_leaf3`: Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_accumulator.rs
> +            let bad_leaf: Digest = H::hash(&8765432165123u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_accumulator.rs
> +                let appends: Vec<Digest> = (2000..2000 + append_size)
Are these magic numbers?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let leaf_hash: Digest = H::hash(&1337u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let another_leaf_hash: Digest = H::hash(&13337u128);
Magic number or random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let new_leaf: Digest = H::hash(&133337u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +            let new_leaf: Digest = H::hash(&133333333333333333333337u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_membership_proof.rs
> +        let new_leaf: Digest = H::hash(&133337u128);
Is this a magic number or a random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_accumulator.rs
> +                    let new_leaf_values: Vec<Digest> = (13..13 + mutate_size)
Are these 13's magic numbers?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_accumulator.rs
> +            let bad_digests: Vec<Digest> = (12..12 + start_size)
Magic number?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/mmr_accumulator.rs
> +            [14, 15, 16, 17].iter().map(|x: &u128| H::hash(x)).collect();
Magic numbers?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/util_types/mmr/archival_mmr.rs
> +        let dummy_digest = H::hash(&0u128);
Magic number or random digest?

2022-10-17 10:48 UTC, Ulrik-dk commented on twenty-first/src/shared_math/rescue_prime_regular.rs
> +        let mut input = [BFieldElement::zero(); 10];
Maybe use `DIGEST_LENGTH*2` here instead of 10.

2022-10-17 11:01 UTC, Sword-Smith commented
It's fine to use so-called magic numbers in tests. Having tests with concrete numbers/values is a test on a level of abstraction that's lower than auto generating values for tests. To convince yourself that something is working, you need, in my opinion, both values that are hardcoded where you can reason about the expected output **and** auto-generated values to have a chance of testing the function more thoroughly.

Declaring values used in tests as constant just increases the indirection when trying to decipher why a test i failing.

Let's say you have an `add` function. Then one of the tests could look like this
```rust
fn test_add_simple() {
    assert_eq!(15, add(8, 7));
    assert_eq!(40000, add(8, 39992));
}
```

Declaring the tests values outside of the test itself (as constant in modular scope or just as separate lines inside the test function) gives worse code. If something fails you want to see the values on the line where the test is called. Declaring the values somewhere else prevents you from doing this.

Of course, if the values are re-used and interlinked, I think it makes sense to have a declaration within a test function as

```rust
fn test_add_simple() {
    let expected_sum = 1337;
    for i in 0..=expected_sum {
        assert_eq!(expected_sum, add(expected_sum - i, i));
    }
}
```

2022-10-18 11:37 UTC, Sword-Smith commented
Looks reasonable to me. I look forward to getting a `Digest` type in here instead of having it in the client software.

2022-10-20 15:02 UTC, Ulrik-dk approved these changes

2022-10-20 15:12 UTC, merged